Repository 8bitzz/COSC2101, pull requests merged in 2021-08, with the labels that each got.

#62 Add some comments on frontend
  frontend/src/App.jsx
  frontend/src/components/movieList/Details.jsx
  frontend/src/components/movieList/FilteredMovieList.jsx
  frontend/src/components/movieList/MovieList.jsx
  frontend/src/components/movieList/SearchMovieList.jsx
  frontend/src/pages/home/Home.jsx
  frontend/src/pages/login/Login.jsx
  frontend/src/pages/signup/Signup.jsx
Labels: documentation

#72 Feat/auth route refractor
  .DS_Store
  .gitignore
  backend/.DS_Store
  backend/src/.DS_Store
  backend/src/controllers/.DS_Store
  backend/src/controllers/userControllers.js
  backend/src/models/user.js
  frontend/public/default.png
Labels: enhancement

#75 Transfer navbar, add logout
  frontend/package-lock.json
  frontend/src/App.jsx
  frontend/src/components/navbar/NavBar.jsx
  frontend/src/pages/login/Login.jsx
  frontend/src/service/auth-context.js
Labels: bug

#80 Fix movie should not unique in cart
  backend/src/models/cart.js
Labels: bug

#81 Feat/Endpoint to remove item in cart
  backend/src/controllers/cartController.js
  backend/src/controllers/userControllers.js
  backend/src/routes/cartRoutes.js
Labels: enhancement

#82 Add UI for Cart Page
  frontend/src/App.jsx
  frontend/src/components/movieItem/MovieItem.jsx
  frontend/src/components/movieList/Details.jsx
  frontend/src/components/movieList/FilteredMovieList.jsx
  frontend/src/components/movieList/MovieList.jsx
  frontend/src/components/movieList/SearchMovieList.jsx
  frontend/src/components/navbar/NavBar.jsx
  frontend/src/pages/cart/Cart.jsx
  frontend/src/pages/home/Home.jsx
Labels: enhancement

#89 Feat/user order
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/errorPopover/ErrorPopover.jsx
  frontend/src/components/movieList/Details.jsx
  frontend/src/components/navbar/NavBar.jsx
  frontend/src/components/order/OrderCard.jsx
  frontend/src/components/order/OrderItem.jsx
  frontend/src/components/spinner/Spinner.jsx
  frontend/src/components/spinner/spinner.css
  frontend/src/components/userDropdown/UserDropdown.jsx
  frontend/src/pages/orderHistory/OrderHistory.jsx
  frontend/src/pages/orderHistory/orderHistory.css
  frontend/src/utils/DateFormatter.js
  package.json
Labels: enhancement

#93 fix uncaught in promise bug when email is registered
  frontend/src/pages/signup/Signup.jsx
Labels: bug

#96 Fix/cart item count
  frontend/src/App.jsx
  frontend/src/components/featured/Featured.jsx
  frontend/src/components/movieItem/MovieItem.jsx
  frontend/src/components/movieList/Details.jsx
  frontend/src/components/movieList/FilteredMovieList.jsx
  frontend/src/components/movieList/SearchMovieList.jsx
  frontend/src/components/navbar/NavBar.jsx
  frontend/src/pages/cart/Cart.jsx
  frontend/src/pages/home/Home.jsx
Labels: bug

#101 User will automatically logged in after signing up successfully
  frontend/src/components/featured/Featured.jsx
  frontend/src/components/movieItem/MovieItem.jsx
  frontend/src/components/movieList/Details.jsx
  frontend/src/components/order/OrderCard.jsx
  frontend/src/pages/login/Login.jsx
  frontend/src/pages/signup/Signup.jsx
Labels: bug

#102 Fix/Round up order amount to 2 decimals
  frontend/src/components/order/OrderCard.jsx
Labels: bug
